### ISSUE TITLE
Database source

### ISSUE THREAD

**Issue by gliwka** [jedisct1/iptoasn-webservice#2]
Hi @jedisct1 ,

thank you for the amazing work!

I'd like to host this webservice by myself on my own infrastructure, but it's not clear to me from where to get the source data.

How do you derrive the source data which you offer on https://iptoasn.com/ for download?

Best,
Matthias

**Comment by uskr** [comment]
I too am curious about the source of the database. My wild guess is that, it is not mentioned by design.

The redistribution of this information is probably against the terms of use of some NICs. Which is a shame. It is the kind of info that should be freely available in a central form (by that I mean all of the NICs combined).

For the complete database, you would have to merge info from all the following RIRs:

- AFRINIC (Africa) http://www.afrinic.net/ whois.afrinic.net
- APNIC (Asia Pacific) http://www.apnic.net/ whois.apnic.net
- ARIN (Northern America) http://www.arin.net/ whois.arin.net
- LACNIC (Latin America and the Carribean) http://www.lacnic.net/ whois.lacnic.net
- RIPE NCC (Europe) www.ripe.net
- IANA IPV4 Recovered Address Space http://www.iana.org/assignments/ipv4-recovered-address-space/ipv4-recovered-address-space.xhtml

Some are more liberal with its terms of use and some are a bit more protective (or should I say political).

One of the many ways to do that is: have a robot query all the allocated ASNs one by one, in a way that doesn't trigger the abuse threshold and build a database. They arent that many, with a single source IP you can probably update the whole database daily. And I believe that is probably fine, if it is for internal use. Not sure about redistributing it.

Disclamer: this is not in any form or shape legal advice.

**Comment by jedisct1** [comment]
It's BGP routes.
